# Introducción

Los procesos de investigación que se insertan en los principios de la Ciencia Abierta han adquirido amplia relevancia en las distintas disciplinas de las ciencias sociales. Durante esta última década, se ha dado un giro disciplinar hacia una mayor transparencia de los diseños de investigación, la recopilación y análisis de datos y también una mayor tendencia hacia la publicación de artículos académicos bajo licencias libres o colaborativas. 

En el caso chileno, este fenómeno también se ha ido posicionando en la agenda científica, tanto así que distintos centros de investigación y otras entidades enfocadas en la divulgación científica ya suscriben a los principales principios y prácticas de la Ciencia Abierta... (mencionar) ... En este sentido, este proyecto de investigación pretende abordar los conocimientos, creencias y prácticas de los y las académicas de las ciencias sociales, con el fin de generar aproximaciones suficientes que permitan evidenciar el estado de avance que ha logrado la Ciencia Abierta en Chile.

A partir de una revisión de literatura de las investigaciones previas, tanto de investigaciones de Ciencias Sociales como investigaciones científicas en general, en el presente informe se pretende dar cuenta de la forma en que han sido llevadas a cabo estas investigaciones, poniendo especial énfasis en los elementos que permitan consolidar la etapa de diseño de esta investigación. En concreto, los principales elementos tomados en consideración tienen que ver con el enmarque disciplinar de cada investigación, el muestreo y población objetivo y con el tipo de preguntas que realizan.
