---
title: "Untitled"
author: "Kevin Carrasco"
date: "16-12-2021"
output: html_document
---

```{r}
pacman::p_load(readxl, dplyr, haven, ggplot2, forcats)

publicaciones <- read_excel("input/data/original/resumen publicaciones.xlsx")
```

```{r}
publicaciones$Anio <- as.numeric(publicaciones$Anio)
publicaciones$disciplina <- as_factor(publicaciones$disciplina)
publicaciones$Componente <- as_factor(publicaciones$Componente)
publicaciones$Pais <- as_factor(publicaciones$Pais)
```

```{r}
graph = round(prop.table(table(Componente=publicaciones$Componente)),3) %>%
  as.data.frame()
graph
```

```{r}
graph2 = round(prop.table(table(Pais=publicaciones$Pais)),3) %>%
  as.data.frame()
```

```{r}
graph3 = round(prop.table(table(Anio=publicaciones$Anio)),3) %>%
  as.data.frame()
```

```{r}
graph4 = round(prop.table(table(disciplina=publicaciones$disciplina)),3) %>%
  as.data.frame()
```

# Componentes

```{r}
comp <- graph %>%
  mutate(name = fct_reorder(Componente, desc(Freq))) %>%
  ggplot(aes(x=name, y=Freq)) +
  geom_bar(stat="identity", fill="#f68060", alpha=.7, width=.5) +
  geom_text(aes(label = paste(round(Freq*100,3),"%")),
            color = "black",
            hjust = -0.1,
            position = position_dodge(width = 0),
            size = 4) +
  scale_y_continuous(limits = c(0, 0.4))+
  coord_flip() +
  xlab("Componente") +
  ylab("Porcentaje de investigaciones") +
  theme_minimal(base_size = 15)
comp

ggsave(comp, file = "output/graphs/componentes.png",device = "png",width = 25,height = 13,dpi = "retina",units = "cm")
```

# Pais

```{r}
Pais <- graph2 %>%
  mutate(name = fct_reorder(Pais, desc(Freq))) %>%
  ggplot( aes(x=name, y=Freq)) +
  geom_bar(stat="identity", fill="#f68060", alpha=.7, width=.5) +
  geom_text(aes(label = paste(round(Freq*100,3),"%")),
            color = "black",
            hjust = -0.1,
            position = position_dodge(width = 0),
            size = 4) +
  coord_flip() +
  xlab("Pais") +
  ylab("Porcentaje de investigaciones") +
  scale_y_continuous(limits = c(0, .4)) +
  theme_minimal(base_size = 15)
Pais

ggsave(Pais, file = "output/graphs/Pais.png",device = "png",width = 25,height = 13,dpi = "retina",units = "cm")
```

# Anio

```{r}
Anio <- graph3 %>%
  ggplot(aes(x=as_factor(Anio), y=Freq)) +
  geom_histogram(stat="identity", fill="#f68060", alpha=.7, width=.5) +
  geom_text(aes(label = paste(round(Freq*100,3),"%")),
            color = "black",
            vjust = -0.5,
            hjust = 0.3,
            position = position_dodge(width = 0),
            size = 4) +
  xlab("Año") +
  ylab("Porcentaje de investigaciones") +
  scale_y_continuous(limits = c(0, .4)) +
  theme_minimal(base_size = 14)
Anio

ggsave(Anio, file = "output/graphs/Anio.png",device = "png",width = 25,height = 13,dpi = "retina",units = "cm")
```

# Disciplina

```{r}
disciplina <- graph4 %>%
  mutate(name = fct_reorder(disciplina, desc(Freq))) %>%
  ggplot( aes(x=name, y=Freq)) +
  geom_bar(stat="identity", fill="#f68060", alpha=.7, width=.5) +
  geom_text(aes(label = paste(round(Freq*100,3),"%")),
            color = "black",
            hjust = -0.1,
            position = position_dodge(width = 0),
            size = 4) +
  coord_flip() +
  xlab("Disciplina") +
  ylab("Porcentaje de investigaciones") +
  scale_y_continuous(limits = c(0, .5)) +
  theme_minimal(base_size = 14)
disciplina

ggsave(disciplina, file = "output/graphs/disciplina.png",device = "png",width = 25,height = 13,dpi = "retina",units = "cm")
```


